# Generated by Django 5.1.4 on 2025-01-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Restaurant', 'Restaurant'), ('Pub', 'Pub'), ('Otro', 'Otro')], max_length=10)),
                ('detalle', models.TextField()),
                ('mapa', models.CharField(max_length=350)),
                ('autor', models.CharField(default='None', max_length=50)),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
            options={
                'db_table': 'entrada',
            },
        ),
    ]
